// <auto-generated />
namespace Vibespace.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatedforICollectionUsage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedforICollectionUsage));
        
        string IMigrationMetadata.Id
        {
            get { return "202101242201113_updated for ICollection Usage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
